In [2]:
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(type(arr))


1
4
(4,)
<class 'numpy.ndarray'>


In [4]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr1


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(type(arr1))

2
8
(2, 4)
<class 'numpy.ndarray'>


In [25]:
arr2=np.zeros((3,4))
arr2
#isse float mai number aaenge

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
arr3=np.ones((3,4))
arr3
#isse float mai number aaenge

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
arr4=np.ones((3,4),dtype=int)# ye likhne se ab float nahi aaega 
arr4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
arr4=np.full((4,3),5) #isse tum apne marji ka koi sa bhi number daal sakte ho 
arr4

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [10]:
arr5=np.arange(0,10,2) # 0 se to 10 tak with gap of 2
arr5

array([0, 2, 4, 6, 8])

In [12]:
arr6=np.linspace(0,1,5) # 0 se lekar 1 tak 5 values jo equal distance par ho 
arr6

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
arr7=np.random.rand(2,3) # 0 se 1 tak random number
arr7

array([[0.68813543, 0.47139525, 0.91482491],
       [0.88264741, 0.00160782, 0.0982434 ]])

In [6]:
import numpy as np
arr8=np.arange(1,7)
arr8


array([1, 2, 3, 4, 5, 6])

In [8]:
arr9=arr8.reshape(2,3) #upar wale arr ko reshape kiya hai and its  necessary to have equal element acc to dimension  
arr9

array([[1, 2, 3],
       [4, 5, 6]])


arr10=np.random.randint(1,5,(2,3))
print(arr10)

In [11]:
arr11=np.arange(1,7).reshape(2,3)
arr11

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
print("Array: ")
arr11
print("Shape: ", arr11.shape)
print("dimnension: ", arr11.ndim)
print("Size: ", arr11.size)
print("type: ", arr11.dtype)


Array: 
Shape:  (2, 3)
dimnension:  2
Size:  6
type:  int64


In [20]:
arr12=np.random.randint(10,100,(3,3))
arr12

array([[65, 24, 90],
       [50, 54, 75],
       [63, 95, 84]], dtype=int32)

In [21]:
arr13=arr12.reshape(9)
arr13

array([65, 24, 90, 50, 54, 75, 63, 95, 84], dtype=int32)

In [22]:
# PART 4 NOW...................................................


In [23]:
arr14 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr14


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [34]:
print(arr14[0,0]) # koi sa bhi element print karwa sakte ho array ka
print(arr14[1])# prints 2 row 
print(arr14[:, 2]) #prints 3 column
    

10
[40 50 60]
[30 60 90]


In [37]:
print(arr14[0:2, 0:2]) #isse samjho ache se thoda confusing hai 

[[10 20]
 [40 50]]


In [41]:
print(arr14[-3]) #negative slicing
print(arr14[:,-3])


[10 20 30]
[10 40 70]


In [42]:
arr14[0,0]=9
arr14

array([[ 9, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [46]:
arr15=np.array([[1,2,3,12],[4,5,6,23],[7,8,9,56]])
arr15


array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 23],
       [ 7,  8,  9, 56]])

In [55]:
print(arr15[1:,2:]) #ye line 37 wala jaise hai...means -> row 1 se end tak and column 2 se end tak

[[ 6 23]
 [ 9 56]]


In [49]:
print(arr15[:2, :3]) # 0 se 1 row tak and 0 se 2nd column tak 

[[1 2 3]
 [4 5 6]]


In [54]:
print(arr15[:,-1:]) # saare rows and last column se end tak 

[[12]
 [23]
 [56]]


In [60]:
print(arr15[:,-1])# ye bhi code 54 ki tarah hai bas output show karne ka tareeka alag hai 

[12 23 56]


In [64]:
import numpy as np
a=np.array([1,2,3,4,5]) #operation on array same for mul and sub
b=np.array([6,7,8,9,10])
print(a+b)
print(a/b)

[ 7  9 11 13 15]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [67]:
print(a+10)
print(a*10)# har element pe apply hoga
print(a**10)

[11 12 13 14 15]
[10 20 30 40 50]
[      1    1024   59049 1048576 9765625]


In [69]:
print(a>20)
print(a==20)

[False False False False False]
[False False False False False]


In [85]:
arr16=np.array([[10, 20, 30], [23, 45, 56]])
arr16
print(arr16.sum())
print(arr16.mean())
print(arr16.max())
print(arr16.min())
print(arr16.std())
print(arr16.sum(axis=0))# har column ka sum if axis=1 then har row ka sum 

184
30.666666666666668
56
10
15.531330342962326
[33 65 86]


In [115]:
arr17=np.array([[23,45,56],[56,23,78],[34,67,89]])
arr17

array([[23, 45, 56],
       [56, 23, 78],
       [34, 67, 89]])

In [125]:
arr18=arr17.mean(axis=0)
arr18
arr19=np.where(arr18<40)[0]
arr19
print("weakest subject is ", arr19)



weakest subject is  [0]
