In [1]:
import numpy as np 


In [9]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [4]:
arr2.shape

(2, 2)

In [5]:
arr2.ndim

2

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
arr.sum(axis=0) #column wise sum

array([4, 6])

In [12]:
arr.sum(axis=1)

array([3, 7])

In [15]:
import pandas as pd
pd.read_csv("joined.csv")

Attendance  Marks
0          90     85
1          85     78
2          88     88
3          97     95

In [17]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Amit","Riya","Karan","Neha"],
    "Marks": [90,85,88,92]
})
print(df)

    Name  Marks
0   Amit     90
1   Riya     85
2  Karan     88
3   Neha     92


In [18]:
df.iloc[2] #index se matching

Name     Karan
Marks       88
Name: 2, dtype: object

In [19]:
df.loc[2] 

Name     Karan
Marks       88
Name: 2, dtype: object

In [20]:
df = df.set_index("Name")
print(df)

       Marks
Name        
Amit      90
Riya      85
Karan     88
Neha      92


In [21]:
df.iloc[2]

Marks    88
Name: Karan, dtype: int64

In [22]:
df.loc["Riya"]

Marks    85
Name: Riya, dtype: int64